# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthHelper
  pod 'Parse'
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'HealthHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealthHelperUITests' do
    # Pods for testing
  end

end
